/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 91
#define ALIAS_COUNT 0
#define TOKEN_COUNT 50
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 30
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_analyzer = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_tokenizers = 5,
  anon_sym_COMMA = 6,
  anon_sym_filters = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  sym_filter_arg = 10,
  anon_sym_table = 11,
  anon_sym_schemafull = 12,
  anon_sym_schemaless = 13,
  anon_sym_drop = 14,
  sym_optional_marker = 15,
  anon_sym_option = 16,
  anon_sym_LT = 17,
  anon_sym_GT = 18,
  anon_sym_array = 19,
  anon_sym_set = 20,
  anon_sym_record = 21,
  anon_sym_geometry = 22,
  anon_sym_PIPE = 23,
  anon_sym_bool = 24,
  anon_sym_int = 25,
  anon_sym_float = 26,
  anon_sym_decimal = 27,
  anon_sym_number = 28,
  anon_sym_string = 29,
  anon_sym_datetime = 30,
  anon_sym_duration = 31,
  anon_sym_uuid = 32,
  anon_sym_bytes = 33,
  anon_sym_any = 34,
  anon_sym_regex = 35,
  anon_sym_object = 36,
  anon_sym_range = 37,
  sym_array_length = 38,
  anon_sym_AT = 39,
  anon_sym_AT_AT = 40,
  anon_sym_COLON = 41,
  anon_sym_LBRACK = 42,
  anon_sym_RBRACK = 43,
  sym_attribute_number = 44,
  anon_sym_true = 45,
  anon_sym_false = 46,
  sym_attribute_string = 47,
  sym_doc_comment_line = 48,
  sym_line_comment = 49,
  sym_source_file = 50,
  sym__definition = 51,
  sym_analyzer_definition = 52,
  sym_analyzer_body = 53,
  sym__analyzer_clause = 54,
  sym_analyzer_tokenizers = 55,
  sym_analyzer_filters = 56,
  sym_filter_call = 57,
  sym_table_definition = 58,
  sym_table_modifier = 59,
  sym_table_body = 60,
  sym_field_definition = 61,
  sym_type_expression = 62,
  sym_type_node = 63,
  sym_option_type = 64,
  sym_array_type = 65,
  sym_set_type = 66,
  sym_record_type = 67,
  sym_geometry_type = 68,
  sym_primitive_type = 69,
  sym_attribute = 70,
  sym_block_attribute = 71,
  sym_attribute_args = 72,
  sym_attribute_kv = 73,
  sym__attribute_value = 74,
  sym_attribute_tuple = 75,
  sym_attribute_array = 76,
  sym_attribute_bool = 77,
  sym_attribute_ident = 78,
  sym_doc_comment = 79,
  aux_sym_source_file_repeat1 = 80,
  aux_sym_analyzer_body_repeat1 = 81,
  aux_sym_analyzer_tokenizers_repeat1 = 82,
  aux_sym_analyzer_filters_repeat1 = 83,
  aux_sym_filter_call_repeat1 = 84,
  aux_sym_table_body_repeat1 = 85,
  aux_sym_field_definition_repeat1 = 86,
  aux_sym_geometry_type_repeat1 = 87,
  aux_sym_attribute_args_repeat1 = 88,
  aux_sym_attribute_tuple_repeat1 = 89,
  aux_sym_doc_comment_repeat1 = 90,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_analyzer] = "analyzer",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_tokenizers] = "tokenizers",
  [anon_sym_COMMA] = ",",
  [anon_sym_filters] = "filters",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_filter_arg] = "filter_arg",
  [anon_sym_table] = "table",
  [anon_sym_schemafull] = "schemafull",
  [anon_sym_schemaless] = "schemaless",
  [anon_sym_drop] = "drop",
  [sym_optional_marker] = "optional_marker",
  [anon_sym_option] = "option",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_array] = "array",
  [anon_sym_set] = "set",
  [anon_sym_record] = "record",
  [anon_sym_geometry] = "geometry",
  [anon_sym_PIPE] = "|",
  [anon_sym_bool] = "bool",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_decimal] = "decimal",
  [anon_sym_number] = "number",
  [anon_sym_string] = "string",
  [anon_sym_datetime] = "datetime",
  [anon_sym_duration] = "duration",
  [anon_sym_uuid] = "uuid",
  [anon_sym_bytes] = "bytes",
  [anon_sym_any] = "any",
  [anon_sym_regex] = "regex",
  [anon_sym_object] = "object",
  [anon_sym_range] = "range",
  [sym_array_length] = "array_length",
  [anon_sym_AT] = "@",
  [anon_sym_AT_AT] = "@@",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_attribute_number] = "attribute_number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_attribute_string] = "attribute_string",
  [sym_doc_comment_line] = "doc_comment_line",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_analyzer_definition] = "analyzer_definition",
  [sym_analyzer_body] = "analyzer_body",
  [sym__analyzer_clause] = "_analyzer_clause",
  [sym_analyzer_tokenizers] = "analyzer_tokenizers",
  [sym_analyzer_filters] = "analyzer_filters",
  [sym_filter_call] = "filter_call",
  [sym_table_definition] = "table_definition",
  [sym_table_modifier] = "table_modifier",
  [sym_table_body] = "table_body",
  [sym_field_definition] = "field_definition",
  [sym_type_expression] = "type_expression",
  [sym_type_node] = "type_node",
  [sym_option_type] = "option_type",
  [sym_array_type] = "array_type",
  [sym_set_type] = "set_type",
  [sym_record_type] = "record_type",
  [sym_geometry_type] = "geometry_type",
  [sym_primitive_type] = "primitive_type",
  [sym_attribute] = "attribute",
  [sym_block_attribute] = "block_attribute",
  [sym_attribute_args] = "attribute_args",
  [sym_attribute_kv] = "attribute_kv",
  [sym__attribute_value] = "_attribute_value",
  [sym_attribute_tuple] = "attribute_tuple",
  [sym_attribute_array] = "attribute_array",
  [sym_attribute_bool] = "attribute_bool",
  [sym_attribute_ident] = "attribute_ident",
  [sym_doc_comment] = "doc_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_analyzer_body_repeat1] = "analyzer_body_repeat1",
  [aux_sym_analyzer_tokenizers_repeat1] = "analyzer_tokenizers_repeat1",
  [aux_sym_analyzer_filters_repeat1] = "analyzer_filters_repeat1",
  [aux_sym_filter_call_repeat1] = "filter_call_repeat1",
  [aux_sym_table_body_repeat1] = "table_body_repeat1",
  [aux_sym_field_definition_repeat1] = "field_definition_repeat1",
  [aux_sym_geometry_type_repeat1] = "geometry_type_repeat1",
  [aux_sym_attribute_args_repeat1] = "attribute_args_repeat1",
  [aux_sym_attribute_tuple_repeat1] = "attribute_tuple_repeat1",
  [aux_sym_doc_comment_repeat1] = "doc_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_analyzer] = anon_sym_analyzer,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_tokenizers] = anon_sym_tokenizers,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_filters] = anon_sym_filters,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_filter_arg] = sym_filter_arg,
  [anon_sym_table] = anon_sym_table,
  [anon_sym_schemafull] = anon_sym_schemafull,
  [anon_sym_schemaless] = anon_sym_schemaless,
  [anon_sym_drop] = anon_sym_drop,
  [sym_optional_marker] = sym_optional_marker,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_geometry] = anon_sym_geometry,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_decimal] = anon_sym_decimal,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_datetime] = anon_sym_datetime,
  [anon_sym_duration] = anon_sym_duration,
  [anon_sym_uuid] = anon_sym_uuid,
  [anon_sym_bytes] = anon_sym_bytes,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_regex] = anon_sym_regex,
  [anon_sym_object] = anon_sym_object,
  [anon_sym_range] = anon_sym_range,
  [sym_array_length] = sym_array_length,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_AT_AT] = anon_sym_AT_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_attribute_number] = sym_attribute_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_attribute_string] = sym_attribute_string,
  [sym_doc_comment_line] = sym_doc_comment_line,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_analyzer_definition] = sym_analyzer_definition,
  [sym_analyzer_body] = sym_analyzer_body,
  [sym__analyzer_clause] = sym__analyzer_clause,
  [sym_analyzer_tokenizers] = sym_analyzer_tokenizers,
  [sym_analyzer_filters] = sym_analyzer_filters,
  [sym_filter_call] = sym_filter_call,
  [sym_table_definition] = sym_table_definition,
  [sym_table_modifier] = sym_table_modifier,
  [sym_table_body] = sym_table_body,
  [sym_field_definition] = sym_field_definition,
  [sym_type_expression] = sym_type_expression,
  [sym_type_node] = sym_type_node,
  [sym_option_type] = sym_option_type,
  [sym_array_type] = sym_array_type,
  [sym_set_type] = sym_set_type,
  [sym_record_type] = sym_record_type,
  [sym_geometry_type] = sym_geometry_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_attribute] = sym_attribute,
  [sym_block_attribute] = sym_block_attribute,
  [sym_attribute_args] = sym_attribute_args,
  [sym_attribute_kv] = sym_attribute_kv,
  [sym__attribute_value] = sym__attribute_value,
  [sym_attribute_tuple] = sym_attribute_tuple,
  [sym_attribute_array] = sym_attribute_array,
  [sym_attribute_bool] = sym_attribute_bool,
  [sym_attribute_ident] = sym_attribute_ident,
  [sym_doc_comment] = sym_doc_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_analyzer_body_repeat1] = aux_sym_analyzer_body_repeat1,
  [aux_sym_analyzer_tokenizers_repeat1] = aux_sym_analyzer_tokenizers_repeat1,
  [aux_sym_analyzer_filters_repeat1] = aux_sym_analyzer_filters_repeat1,
  [aux_sym_filter_call_repeat1] = aux_sym_filter_call_repeat1,
  [aux_sym_table_body_repeat1] = aux_sym_table_body_repeat1,
  [aux_sym_field_definition_repeat1] = aux_sym_field_definition_repeat1,
  [aux_sym_geometry_type_repeat1] = aux_sym_geometry_type_repeat1,
  [aux_sym_attribute_args_repeat1] = aux_sym_attribute_args_repeat1,
  [aux_sym_attribute_tuple_repeat1] = aux_sym_attribute_tuple_repeat1,
  [aux_sym_doc_comment_repeat1] = aux_sym_doc_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_analyzer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tokenizers] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filters] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_filter_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schemafull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schemaless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_drop] = {
    .visible = true,
    .named = false,
  },
  [sym_optional_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_geometry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decimal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_duration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uuid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bytes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_regex] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_object] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [sym_array_length] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_string] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_analyzer_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_analyzer_body] = {
    .visible = true,
    .named = true,
  },
  [sym__analyzer_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_analyzer_tokenizers] = {
    .visible = true,
    .named = true,
  },
  [sym_analyzer_filters] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_call] = {
    .visible = true,
    .named = true,
  },
  [sym_table_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_table_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_table_body] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_type_node] = {
    .visible = true,
    .named = true,
  },
  [sym_option_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_set_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_geometry_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_block_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_args] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_kv] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_array] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_analyzer_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_analyzer_tokenizers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_analyzer_filters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filter_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_geometry_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_args = 2,
  field_attribute = 3,
  field_base = 4,
  field_body = 5,
  field_call = 6,
  field_feature = 7,
  field_inner = 8,
  field_key = 9,
  field_length = 10,
  field_modifier = 11,
  field_name = 12,
  field_table = 13,
  field_type = 14,
  field_value = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_args] = "args",
  [field_attribute] = "attribute",
  [field_base] = "base",
  [field_body] = "body",
  [field_call] = "call",
  [field_feature] = "feature",
  [field_inner] = "inner",
  [field_key] = "key",
  [field_length] = "length",
  [field_modifier] = "modifier",
  [field_name] = "name",
  [field_table] = "table",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 1},
  [5] = {.index = 8, .length = 1},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 1},
  [14] = {.index = 23, .length = 3},
  [15] = {.index = 26, .length = 2},
  [16] = {.index = 28, .length = 2},
  [17] = {.index = 30, .length = 2},
  [18] = {.index = 32, .length = 2},
  [19] = {.index = 34, .length = 1},
  [20] = {.index = 35, .length = 1},
  [21] = {.index = 36, .length = 1},
  [22] = {.index = 37, .length = 1},
  [23] = {.index = 38, .length = 3},
  [24] = {.index = 41, .length = 2},
  [25] = {.index = 43, .length = 2},
  [26] = {.index = 45, .length = 1},
  [27] = {.index = 46, .length = 2},
  [28] = {.index = 48, .length = 2},
  [29] = {.index = 50, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 1},
  [2] =
    {field_body, 3},
    {field_modifier, 2},
    {field_name, 1},
  [5] =
    {field_body, 3},
    {field_name, 2},
  [7] =
    {field_name, 1},
  [8] =
    {field_name, 0},
  [9] =
    {field_call, 1},
  [10] =
    {field_name, 0},
    {field_type, 1},
  [12] =
    {field_base, 0},
  [13] =
    {field_body, 4},
    {field_modifier, 3},
    {field_name, 2},
  [16] =
    {field_name, 1},
    {field_name, 2, .inherited = true},
  [18] =
    {field_call, 1},
    {field_call, 2, .inherited = true},
  [20] =
    {field_args, 2},
    {field_name, 1},
  [22] =
    {field_attribute, 0},
  [23] =
    {field_attribute, 2, .inherited = true},
    {field_name, 0},
    {field_type, 1},
  [26] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [28] =
    {field_call, 0, .inherited = true},
    {field_call, 1, .inherited = true},
  [30] =
    {field_attribute, 0, .inherited = true},
    {field_attribute, 1, .inherited = true},
  [32] =
    {field_arg, 2},
    {field_name, 0},
  [34] =
    {field_inner, 2},
  [35] =
    {field_table, 2},
  [36] =
    {field_feature, 2},
  [37] =
    {field_arg, 1},
  [38] =
    {field_arg, 2},
    {field_arg, 3, .inherited = true},
    {field_name, 0},
  [41] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
  [43] =
    {field_key, 0},
    {field_value, 2},
  [45] =
    {field_feature, 1},
  [46] =
    {field_feature, 2},
    {field_feature, 3, .inherited = true},
  [48] =
    {field_feature, 0, .inherited = true},
    {field_feature, 1, .inherited = true},
  [50] =
    {field_inner, 2},
    {field_length, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '(', 12,
        ')', 13,
        ',', 11,
        '/', 2,
        ':', 23,
        '<', 16,
        '>', 17,
        '?', 15,
        '@', 21,
        '[', 24,
        ']', 25,
        '{', 9,
        '|', 18,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '(', 12,
        ')', 13,
        ',', 11,
        '/', 3,
        ':', 23,
        '<', 16,
        '>', 17,
        '?', 15,
        '@', 21,
        '[', 24,
        ']', 25,
        '{', 9,
        '|', 18,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_filter_arg);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_optional_marker);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_array_length);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_array_length);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '@') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_AT_AT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_attribute_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_string);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_doc_comment_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'd', 3,
        'f', 4,
        'g', 5,
        'i', 6,
        'n', 7,
        'o', 8,
        'r', 9,
        's', 10,
        't', 11,
        'u', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(13);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(27);
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'y') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead == 'j') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(56);
      if (lookahead == 'g') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 34:
      if (lookahead == 'b') ADVANCE(61);
      END_STATE();
    case 35:
      if (lookahead == 'k') ADVANCE(62);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 49:
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 50:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 52:
      if (lookahead == 'b') ADVANCE(77);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 55:
      if (lookahead == 'g') ADVANCE(80);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 64:
      if (lookahead == 'd') ADVANCE(88);
      END_STATE();
    case 65:
      if (lookahead == 'y') ADVANCE(89);
      END_STATE();
    case 66:
      if (lookahead == 'y') ADVANCE(90);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 68:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 70:
      if (lookahead == 'm') ADVANCE(93);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_drop);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 77:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 78:
      if (lookahead == 'c') ADVANCE(100);
      END_STATE();
    case 79:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(103);
      END_STATE();
    case 82:
      if (lookahead == 'x') ADVANCE(104);
      END_STATE();
    case 83:
      if (lookahead == 'm') ADVANCE(105);
      END_STATE();
    case 84:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_uuid);
      END_STATE();
    case 89:
      if (lookahead == 'z') ADVANCE(109);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_bytes);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(110);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(111);
      END_STATE();
    case 94:
      if (lookahead == 'i') ADVANCE(112);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(113);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 99:
      if (lookahead == 'r') ADVANCE(115);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 103:
      if (lookahead == 'd') ADVANCE(118);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_regex);
      END_STATE();
    case 105:
      if (lookahead == 'a') ADVANCE(119);
      END_STATE();
    case 106:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_table);
      END_STATE();
    case 108:
      if (lookahead == 'i') ADVANCE(121);
      END_STATE();
    case 109:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 110:
      if (lookahead == 'm') ADVANCE(123);
      END_STATE();
    case 111:
      if (lookahead == 'l') ADVANCE(124);
      END_STATE();
    case 112:
      if (lookahead == 'o') ADVANCE(125);
      END_STATE();
    case 113:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 114:
      if (lookahead == 'r') ADVANCE(127);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_object);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 119:
      if (lookahead == 'f') ADVANCE(128);
      if (lookahead == 'l') ADVANCE(129);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 121:
      if (lookahead == 'z') ADVANCE(130);
      END_STATE();
    case 122:
      if (lookahead == 'r') ADVANCE(131);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_decimal);
      END_STATE();
    case 125:
      if (lookahead == 'n') ADVANCE(133);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_filters);
      END_STATE();
    case 127:
      if (lookahead == 'y') ADVANCE(134);
      END_STATE();
    case 128:
      if (lookahead == 'u') ADVANCE(135);
      END_STATE();
    case 129:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(137);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_analyzer);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_duration);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_geometry);
      END_STATE();
    case 135:
      if (lookahead == 'l') ADVANCE(138);
      END_STATE();
    case 136:
      if (lookahead == 's') ADVANCE(139);
      END_STATE();
    case 137:
      if (lookahead == 'r') ADVANCE(140);
      END_STATE();
    case 138:
      if (lookahead == 'l') ADVANCE(141);
      END_STATE();
    case 139:
      if (lookahead == 's') ADVANCE(142);
      END_STATE();
    case 140:
      if (lookahead == 's') ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_schemafull);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_schemaless);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_tokenizers);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 7},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 7},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 7},
  [94] = {.lex_state = 7},
  [95] = {.lex_state = 7},
  [96] = {.lex_state = 7},
  [97] = {.lex_state = 7},
  [98] = {.lex_state = 7},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 7},
  [101] = {.lex_state = 7},
  [102] = {.lex_state = 7},
  [103] = {.lex_state = 7},
  [104] = {.lex_state = 7},
  [105] = {.lex_state = 7},
  [106] = {.lex_state = 7},
  [107] = {.lex_state = 4},
  [108] = {.lex_state = 7},
  [109] = {.lex_state = 4},
  [110] = {.lex_state = 5},
  [111] = {.lex_state = 7},
  [112] = {.lex_state = 7},
  [113] = {.lex_state = 7},
  [114] = {.lex_state = 7},
  [115] = {.lex_state = 7},
  [116] = {.lex_state = 7},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 7},
  [119] = {.lex_state = 7},
  [120] = {.lex_state = 7},
  [121] = {.lex_state = 7},
  [122] = {.lex_state = 7},
  [123] = {.lex_state = 7},
  [124] = {.lex_state = 7},
  [125] = {.lex_state = 7},
  [126] = {.lex_state = 7},
  [127] = {.lex_state = 7},
  [128] = {.lex_state = 7},
  [129] = {.lex_state = 7},
  [130] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_analyzer] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_tokenizers] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_filters] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_table] = ACTIONS(1),
    [anon_sym_schemafull] = ACTIONS(1),
    [anon_sym_schemaless] = ACTIONS(1),
    [anon_sym_drop] = ACTIONS(1),
    [sym_optional_marker] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_geometry] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_decimal] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [anon_sym_duration] = ACTIONS(1),
    [anon_sym_uuid] = ACTIONS(1),
    [anon_sym_bytes] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_regex] = ACTIONS(1),
    [anon_sym_object] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [sym_array_length] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_AT_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_attribute_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_attribute_string] = ACTIONS(1),
    [sym_doc_comment_line] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(108),
    [sym__definition] = STATE(10),
    [sym_analyzer_definition] = STATE(10),
    [sym_table_definition] = STATE(10),
    [sym_doc_comment] = STATE(101),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_doc_comment_repeat1] = STATE(50),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_analyzer] = ACTIONS(7),
    [anon_sym_table] = ACTIONS(9),
    [sym_doc_comment_line] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      anon_sym_option,
    ACTIONS(15), 1,
      anon_sym_array,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(19), 1,
      anon_sym_record,
    ACTIONS(21), 1,
      anon_sym_geometry,
    ACTIONS(25), 1,
      sym_line_comment,
    STATE(31), 1,
      sym_type_expression,
    STATE(35), 1,
      sym_type_node,
    STATE(15), 6,
      sym_option_type,
      sym_array_type,
      sym_set_type,
      sym_record_type,
      sym_geometry_type,
      sym_primitive_type,
    ACTIONS(23), 14,
      anon_sym_bool,
      anon_sym_int,
      anon_sym_float,
      anon_sym_decimal,
      anon_sym_number,
      anon_sym_string,
      anon_sym_datetime,
      anon_sym_duration,
      anon_sym_uuid,
      anon_sym_bytes,
      anon_sym_any,
      anon_sym_regex,
      anon_sym_object,
      anon_sym_range,
  [49] = 9,
    ACTIONS(13), 1,
      anon_sym_option,
    ACTIONS(15), 1,
      anon_sym_array,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(19), 1,
      anon_sym_record,
    ACTIONS(21), 1,
      anon_sym_geometry,
    ACTIONS(25), 1,
      sym_line_comment,
    STATE(99), 1,
      sym_type_node,
    STATE(15), 6,
      sym_option_type,
      sym_array_type,
      sym_set_type,
      sym_record_type,
      sym_geometry_type,
      sym_primitive_type,
    ACTIONS(23), 14,
      anon_sym_bool,
      anon_sym_int,
      anon_sym_float,
      anon_sym_decimal,
      anon_sym_number,
      anon_sym_string,
      anon_sym_datetime,
      anon_sym_duration,
      anon_sym_uuid,
      anon_sym_bytes,
      anon_sym_any,
      anon_sym_regex,
      anon_sym_object,
      anon_sym_range,
  [95] = 9,
    ACTIONS(13), 1,
      anon_sym_option,
    ACTIONS(15), 1,
      anon_sym_array,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(19), 1,
      anon_sym_record,
    ACTIONS(21), 1,
      anon_sym_geometry,
    ACTIONS(25), 1,
      sym_line_comment,
    STATE(118), 1,
      sym_type_node,
    STATE(15), 6,
      sym_option_type,
      sym_array_type,
      sym_set_type,
      sym_record_type,
      sym_geometry_type,
      sym_primitive_type,
    ACTIONS(23), 14,
      anon_sym_bool,
      anon_sym_int,
      anon_sym_float,
      anon_sym_decimal,
      anon_sym_number,
      anon_sym_string,
      anon_sym_datetime,
      anon_sym_duration,
      anon_sym_uuid,
      anon_sym_bytes,
      anon_sym_any,
      anon_sym_regex,
      anon_sym_object,
      anon_sym_range,
  [141] = 9,
    ACTIONS(13), 1,
      anon_sym_option,
    ACTIONS(15), 1,
      anon_sym_array,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(19), 1,
      anon_sym_record,
    ACTIONS(21), 1,
      anon_sym_geometry,
    ACTIONS(25), 1,
      sym_line_comment,
    STATE(103), 1,
      sym_type_node,
    STATE(15), 6,
      sym_option_type,
      sym_array_type,
      sym_set_type,
      sym_record_type,
      sym_geometry_type,
      sym_primitive_type,
    ACTIONS(23), 14,
      anon_sym_bool,
      anon_sym_int,
      anon_sym_float,
      anon_sym_decimal,
      anon_sym_number,
      anon_sym_string,
      anon_sym_datetime,
      anon_sym_duration,
      anon_sym_uuid,
      anon_sym_bytes,
      anon_sym_any,
      anon_sym_regex,
      anon_sym_object,
      anon_sym_range,
  [187] = 8,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 2,
      sym_attribute_number,
      sym_attribute_string,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(82), 5,
      sym__attribute_value,
      sym_attribute_tuple,
      sym_attribute_array,
      sym_attribute_bool,
      sym_attribute_ident,
  [218] = 8,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(41), 2,
      sym_attribute_number,
      sym_attribute_string,
    STATE(84), 5,
      sym__attribute_value,
      sym_attribute_tuple,
      sym_attribute_array,
      sym_attribute_bool,
      sym_attribute_ident,
  [249] = 7,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(43), 2,
      sym_attribute_number,
      sym_attribute_string,
    STATE(104), 5,
      sym__attribute_value,
      sym_attribute_tuple,
      sym_attribute_array,
      sym_attribute_bool,
      sym_attribute_ident,
  [277] = 7,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_attribute_number,
      sym_attribute_string,
    STATE(88), 5,
      sym__attribute_value,
      sym_attribute_tuple,
      sym_attribute_array,
      sym_attribute_bool,
      sym_attribute_ident,
  [305] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_analyzer,
    ACTIONS(9), 1,
      anon_sym_table,
    ACTIONS(11), 1,
      sym_doc_comment_line,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      aux_sym_doc_comment_repeat1,
    STATE(101), 1,
      sym_doc_comment,
    STATE(11), 4,
      sym__definition,
      sym_analyzer_definition,
      sym_table_definition,
      aux_sym_source_file_repeat1,
  [333] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_analyzer,
    ACTIONS(54), 1,
      anon_sym_table,
    ACTIONS(57), 1,
      sym_doc_comment_line,
    STATE(50), 1,
      aux_sym_doc_comment_repeat1,
    STATE(101), 1,
      sym_doc_comment,
    STATE(11), 4,
      sym__definition,
      sym_analyzer_definition,
      sym_table_definition,
      aux_sym_source_file_repeat1,
  [361] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(62), 1,
      anon_sym_LT,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(60), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [379] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 1,
      anon_sym_tokenizers,
    ACTIONS(70), 1,
      anon_sym_filters,
    STATE(17), 4,
      sym__analyzer_clause,
      sym_analyzer_tokenizers,
      sym_analyzer_filters,
      aux_sym_analyzer_body_repeat1,
  [398] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(68), 1,
      anon_sym_tokenizers,
    ACTIONS(70), 1,
      anon_sym_filters,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(13), 4,
      sym__analyzer_clause,
      sym_analyzer_tokenizers,
      sym_analyzer_filters,
      aux_sym_analyzer_body_repeat1,
  [417] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(76), 1,
      anon_sym_AT,
    ACTIONS(74), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [432] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(80), 1,
      anon_sym_AT,
    ACTIONS(78), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [447] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      anon_sym_tokenizers,
    ACTIONS(87), 1,
      anon_sym_filters,
    STATE(17), 4,
      sym__analyzer_clause,
      sym_analyzer_tokenizers,
      sym_analyzer_filters,
      aux_sym_analyzer_body_repeat1,
  [466] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(92), 1,
      anon_sym_AT,
    ACTIONS(90), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [481] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(96), 1,
      anon_sym_AT,
    ACTIONS(94), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [496] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(100), 1,
      anon_sym_AT,
    ACTIONS(98), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [511] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(104), 1,
      anon_sym_AT,
    ACTIONS(102), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [526] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(108), 1,
      anon_sym_AT,
    ACTIONS(106), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [541] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(112), 1,
      anon_sym_AT,
    ACTIONS(110), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [556] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(116), 1,
      anon_sym_AT,
    ACTIONS(114), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [571] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(120), 1,
      anon_sym_AT,
    ACTIONS(118), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_optional_marker,
      anon_sym_GT,
      anon_sym_AT_AT,
      sym_identifier,
  [586] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(124), 1,
      anon_sym_AT,
    STATE(34), 1,
      aux_sym_field_definition_repeat1,
    STATE(48), 1,
      sym_attribute,
    ACTIONS(122), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [604] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    ACTIONS(130), 1,
      anon_sym_AT_AT,
    STATE(32), 3,
      sym_field_definition,
      sym_block_attribute,
      aux_sym_table_body_repeat1,
  [622] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 1,
      anon_sym_AT_AT,
    STATE(28), 3,
      sym_field_definition,
      sym_block_attribute,
      aux_sym_table_body_repeat1,
  [640] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_table_body,
    STATE(100), 1,
      sym_table_modifier,
    ACTIONS(142), 3,
      anon_sym_schemafull,
      anon_sym_schemaless,
      anon_sym_drop,
  [658] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
    ACTIONS(148), 1,
      anon_sym_AT,
    STATE(63), 1,
      sym_attribute_args,
    ACTIONS(144), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [676] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(124), 1,
      anon_sym_AT,
    STATE(26), 1,
      aux_sym_field_definition_repeat1,
    STATE(48), 1,
      sym_attribute,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [694] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(130), 1,
      anon_sym_AT_AT,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    STATE(28), 3,
      sym_field_definition,
      sym_block_attribute,
      aux_sym_table_body_repeat1,
  [712] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_table_body,
    STATE(97), 1,
      sym_table_modifier,
    ACTIONS(142), 3,
      anon_sym_schemafull,
      anon_sym_schemaless,
      anon_sym_drop,
  [730] = 5,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(156), 1,
      anon_sym_AT,
    STATE(34), 1,
      aux_sym_field_definition_repeat1,
    STATE(48), 1,
      sym_attribute,
    ACTIONS(154), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [748] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(161), 1,
      sym_optional_marker,
    ACTIONS(163), 1,
      anon_sym_AT,
    ACTIONS(159), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [763] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_analyzer_filters_repeat1,
    ACTIONS(165), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [778] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_analyzer_tokenizers_repeat1,
    ACTIONS(170), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [793] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_analyzer_tokenizers_repeat1,
    ACTIONS(175), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [808] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_analyzer_filters_repeat1,
    ACTIONS(179), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [823] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 4,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_COMMA,
      anon_sym_filters,
  [836] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
    STATE(75), 1,
      sym_attribute_args,
    ACTIONS(187), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [851] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_analyzer_tokenizers_repeat1,
    ACTIONS(189), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [866] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_analyzer_filters_repeat1,
    ACTIONS(191), 3,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_filters,
  [881] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [891] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [901] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(199), 1,
      anon_sym_AT,
    ACTIONS(197), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [913] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(201), 4,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_COMMA,
      anon_sym_filters,
  [923] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(205), 1,
      anon_sym_AT,
    ACTIONS(203), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [935] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(207), 4,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_COMMA,
      anon_sym_filters,
  [945] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(211), 1,
      sym_doc_comment_line,
    STATE(55), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(209), 2,
      anon_sym_analyzer,
      anon_sym_table,
  [959] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(215), 1,
      anon_sym_AT,
    ACTIONS(213), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [971] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [981] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [991] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(221), 4,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_COMMA,
      anon_sym_filters,
  [1001] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(225), 1,
      sym_doc_comment_line,
    STATE(55), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(223), 2,
      anon_sym_analyzer,
      anon_sym_table,
  [1015] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(230), 1,
      anon_sym_AT,
    ACTIONS(228), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(232), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1037] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(234), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(236), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1057] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_AT,
    ACTIONS(238), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [1069] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(242), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1079] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(244), 4,
      anon_sym_RBRACE,
      anon_sym_tokenizers,
      anon_sym_COMMA,
      anon_sym_filters,
  [1089] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      anon_sym_AT,
    ACTIONS(246), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [1101] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1111] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(252), 4,
      ts_builtin_sym_end,
      anon_sym_analyzer,
      anon_sym_table,
      sym_doc_comment_line,
  [1121] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_attribute_tuple_repeat1,
    ACTIONS(257), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1135] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_attribute_tuple_repeat1,
  [1148] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_filter_call_repeat1,
  [1161] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_attribute_args_repeat1,
  [1174] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(271), 1,
      anon_sym_GT,
    ACTIONS(273), 1,
      anon_sym_PIPE,
    STATE(73), 1,
      aux_sym_geometry_type_repeat1,
  [1187] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_filter_call_repeat1,
  [1200] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_attribute_args_repeat1,
  [1213] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(273), 1,
      anon_sym_PIPE,
    ACTIONS(279), 1,
      anon_sym_GT,
    STATE(80), 1,
      aux_sym_geometry_type_repeat1,
  [1226] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(281), 1,
      sym_identifier,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_attribute_kv,
  [1239] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(285), 3,
      anon_sym_RBRACE,
      anon_sym_AT_AT,
      sym_identifier,
  [1248] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_filter_call_repeat1,
  [1261] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(292), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1270] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(294), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1279] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_attribute_args_repeat1,
  [1292] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(301), 1,
      anon_sym_GT,
    ACTIONS(303), 1,
      anon_sym_PIPE,
    STATE(80), 1,
      aux_sym_geometry_type_repeat1,
  [1305] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(306), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1314] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_attribute_tuple_repeat1,
  [1327] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(310), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1336] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_attribute_tuple_repeat1,
  [1349] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(314), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1358] = 4,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_attribute_tuple_repeat1,
  [1371] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(318), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1380] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(257), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1389] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(320), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1398] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(322), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1407] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1415] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(324), 1,
      sym_identifier,
    STATE(39), 1,
      sym_filter_call,
  [1425] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_analyzer_body,
  [1435] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(328), 2,
      anon_sym_GT,
      anon_sym_PIPE,
  [1443] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(324), 1,
      sym_identifier,
    STATE(49), 1,
      sym_filter_call,
  [1453] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_analyzer_body,
  [1463] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym_table_body,
  [1473] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(330), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1481] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(332), 1,
      anon_sym_COMMA,
    ACTIONS(334), 1,
      anon_sym_GT,
  [1491] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_table_body,
  [1501] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(336), 1,
      anon_sym_analyzer,
    ACTIONS(338), 1,
      anon_sym_table,
  [1511] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(91), 1,
      sym_attribute_kv,
  [1521] = 3,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_GT,
  [1531] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(344), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1539] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(346), 1,
      sym_identifier,
  [1546] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(348), 1,
      sym_identifier,
  [1553] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(350), 1,
      sym_array_length,
  [1560] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(352), 1,
      ts_builtin_sym_end,
  [1567] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(354), 1,
      sym_array_length,
  [1574] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(356), 1,
      sym_filter_arg,
  [1581] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(358), 1,
      anon_sym_GT,
  [1588] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(360), 1,
      anon_sym_GT,
  [1595] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(362), 1,
      anon_sym_LBRACE,
  [1602] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(364), 1,
      sym_identifier,
  [1609] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(366), 1,
      anon_sym_LT,
  [1616] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(368), 1,
      sym_identifier,
  [1623] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(370), 1,
      sym_filter_arg,
  [1630] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(372), 1,
      anon_sym_GT,
  [1637] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(374), 1,
      anon_sym_LT,
  [1644] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(376), 1,
      sym_identifier,
  [1651] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(378), 1,
      sym_identifier,
  [1658] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(380), 1,
      sym_identifier,
  [1665] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(382), 1,
      anon_sym_COLON,
  [1672] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(384), 1,
      anon_sym_GT,
  [1679] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(386), 1,
      sym_identifier,
  [1686] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(388), 1,
      anon_sym_LT,
  [1693] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(390), 1,
      sym_identifier,
  [1700] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(392), 1,
      sym_identifier,
  [1707] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(394), 1,
      anon_sym_LT,
  [1714] = 2,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(396), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 95,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 187,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 249,
  [SMALL_STATE(9)] = 277,
  [SMALL_STATE(10)] = 305,
  [SMALL_STATE(11)] = 333,
  [SMALL_STATE(12)] = 361,
  [SMALL_STATE(13)] = 379,
  [SMALL_STATE(14)] = 398,
  [SMALL_STATE(15)] = 417,
  [SMALL_STATE(16)] = 432,
  [SMALL_STATE(17)] = 447,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 481,
  [SMALL_STATE(20)] = 496,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 526,
  [SMALL_STATE(23)] = 541,
  [SMALL_STATE(24)] = 556,
  [SMALL_STATE(25)] = 571,
  [SMALL_STATE(26)] = 586,
  [SMALL_STATE(27)] = 604,
  [SMALL_STATE(28)] = 622,
  [SMALL_STATE(29)] = 640,
  [SMALL_STATE(30)] = 658,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 694,
  [SMALL_STATE(33)] = 712,
  [SMALL_STATE(34)] = 730,
  [SMALL_STATE(35)] = 748,
  [SMALL_STATE(36)] = 763,
  [SMALL_STATE(37)] = 778,
  [SMALL_STATE(38)] = 793,
  [SMALL_STATE(39)] = 808,
  [SMALL_STATE(40)] = 823,
  [SMALL_STATE(41)] = 836,
  [SMALL_STATE(42)] = 851,
  [SMALL_STATE(43)] = 866,
  [SMALL_STATE(44)] = 881,
  [SMALL_STATE(45)] = 891,
  [SMALL_STATE(46)] = 901,
  [SMALL_STATE(47)] = 913,
  [SMALL_STATE(48)] = 923,
  [SMALL_STATE(49)] = 935,
  [SMALL_STATE(50)] = 945,
  [SMALL_STATE(51)] = 959,
  [SMALL_STATE(52)] = 971,
  [SMALL_STATE(53)] = 981,
  [SMALL_STATE(54)] = 991,
  [SMALL_STATE(55)] = 1001,
  [SMALL_STATE(56)] = 1015,
  [SMALL_STATE(57)] = 1027,
  [SMALL_STATE(58)] = 1037,
  [SMALL_STATE(59)] = 1047,
  [SMALL_STATE(60)] = 1057,
  [SMALL_STATE(61)] = 1069,
  [SMALL_STATE(62)] = 1079,
  [SMALL_STATE(63)] = 1089,
  [SMALL_STATE(64)] = 1101,
  [SMALL_STATE(65)] = 1111,
  [SMALL_STATE(66)] = 1121,
  [SMALL_STATE(67)] = 1135,
  [SMALL_STATE(68)] = 1148,
  [SMALL_STATE(69)] = 1161,
  [SMALL_STATE(70)] = 1174,
  [SMALL_STATE(71)] = 1187,
  [SMALL_STATE(72)] = 1200,
  [SMALL_STATE(73)] = 1213,
  [SMALL_STATE(74)] = 1226,
  [SMALL_STATE(75)] = 1239,
  [SMALL_STATE(76)] = 1248,
  [SMALL_STATE(77)] = 1261,
  [SMALL_STATE(78)] = 1270,
  [SMALL_STATE(79)] = 1279,
  [SMALL_STATE(80)] = 1292,
  [SMALL_STATE(81)] = 1305,
  [SMALL_STATE(82)] = 1314,
  [SMALL_STATE(83)] = 1327,
  [SMALL_STATE(84)] = 1336,
  [SMALL_STATE(85)] = 1349,
  [SMALL_STATE(86)] = 1358,
  [SMALL_STATE(87)] = 1371,
  [SMALL_STATE(88)] = 1380,
  [SMALL_STATE(89)] = 1389,
  [SMALL_STATE(90)] = 1398,
  [SMALL_STATE(91)] = 1407,
  [SMALL_STATE(92)] = 1415,
  [SMALL_STATE(93)] = 1425,
  [SMALL_STATE(94)] = 1435,
  [SMALL_STATE(95)] = 1443,
  [SMALL_STATE(96)] = 1453,
  [SMALL_STATE(97)] = 1463,
  [SMALL_STATE(98)] = 1473,
  [SMALL_STATE(99)] = 1481,
  [SMALL_STATE(100)] = 1491,
  [SMALL_STATE(101)] = 1501,
  [SMALL_STATE(102)] = 1511,
  [SMALL_STATE(103)] = 1521,
  [SMALL_STATE(104)] = 1531,
  [SMALL_STATE(105)] = 1539,
  [SMALL_STATE(106)] = 1546,
  [SMALL_STATE(107)] = 1553,
  [SMALL_STATE(108)] = 1560,
  [SMALL_STATE(109)] = 1567,
  [SMALL_STATE(110)] = 1574,
  [SMALL_STATE(111)] = 1581,
  [SMALL_STATE(112)] = 1588,
  [SMALL_STATE(113)] = 1595,
  [SMALL_STATE(114)] = 1602,
  [SMALL_STATE(115)] = 1609,
  [SMALL_STATE(116)] = 1616,
  [SMALL_STATE(117)] = 1623,
  [SMALL_STATE(118)] = 1630,
  [SMALL_STATE(119)] = 1637,
  [SMALL_STATE(120)] = 1644,
  [SMALL_STATE(121)] = 1651,
  [SMALL_STATE(122)] = 1658,
  [SMALL_STATE(123)] = 1665,
  [SMALL_STATE(124)] = 1672,
  [SMALL_STATE(125)] = 1679,
  [SMALL_STATE(126)] = 1686,
  [SMALL_STATE(127)] = 1693,
  [SMALL_STATE(128)] = 1700,
  [SMALL_STATE(129)] = 1707,
  [SMALL_STATE(130)] = 1714,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_node, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_node, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_analyzer_body_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_analyzer_body_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_analyzer_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 20),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 4, 0, 20),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_type, 4, 0, 19),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option_type, 4, 0, 19),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 4, 0, 19),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_type, 4, 0, 19),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 4, 0, 19),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 4, 0, 19),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 6, 0, 29),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 6, 0, 29),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 6, 0, 29),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_type, 6, 0, 29),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_geometry_type, 5, 0, 27),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_geometry_type, 5, 0, 27),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_geometry_type, 4, 0, 21),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_geometry_type, 4, 0, 21),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 3, 0, 14),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_body_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_body_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 2, 0, 7),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_definition_repeat1, 2, 0, 17),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_definition_repeat1, 2, 0, 17), SHIFT_REPEAT(121),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_expression, 1, 0, 8),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_expression, 1, 0, 8),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_analyzer_filters_repeat1, 2, 0, 16),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_analyzer_filters_repeat1, 2, 0, 16), SHIFT_REPEAT(95),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_analyzer_tokenizers_repeat1, 2, 0, 15),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_analyzer_tokenizers_repeat1, 2, 0, 15), SHIFT_REPEAT(130),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_tokenizers, 3, 0, 10),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_filters, 2, 0, 6),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_call, 1, 0, 5),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_attribute, 2, 0, 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_tokenizers, 2, 0, 4),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_filters, 3, 0, 11),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_body, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_body, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_expression, 2, 0, 8),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_expression, 2, 0, 8),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_analyzer_tokenizers_repeat1, 2, 0, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_definition_repeat1, 1, 0, 13),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_definition_repeat1, 1, 0, 13),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_analyzer_filters_repeat1, 2, 0, 6),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_args, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_args, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 3, 0, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 5, 0, 9),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_call, 4, 0, 18),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_args, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_args, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 4, 0, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 4, 0, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_definition, 4, 0, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_args, 4, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_args, 4, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_body, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_call, 5, 0, 23),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 12),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 12),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_analyzer_definition, 3, 0, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_body, 3, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_tuple_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_attribute, 3, 0, 12),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filter_call_repeat1, 2, 0, 24), SHIFT_REPEAT(117),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_call_repeat1, 2, 0, 24),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_bool, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_ident, 1, 0, 0),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_args_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_args_repeat1, 2, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_geometry_type_repeat1, 2, 0, 28),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_geometry_type_repeat1, 2, 0, 28), SHIFT_REPEAT(116),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_tuple, 2, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_array, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_tuple, 3, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_array, 3, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_tuple, 4, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_array, 4, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_geometry_type_repeat1, 2, 0, 26),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_call_repeat1, 2, 0, 22),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_kv, 3, 0, 25),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [352] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_modifier, 1, 0, 0),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aurora(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "aurora",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
