$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  toolchains: ['rust']

fileGroups:
  sources:
    - 'src/**/*.rs'
    - 'Cargo.toml'
  tests:
    - 'tests/**/*.rs'
    - 'benches/**/*.rs'
    - '**/Cargo.toml'

tasks:
  build:
    command: 'cargo'
    args:
      - 'build'
      - '--manifest-path'
      - '$projectRoot/Cargo.toml'
    inputs:
      - '@globs(sources)'
      - '/Cargo.toml'
      - '/Cargo.lock'
      - '/rust-toolchain.toml'

  check:
    command: 'cargo'
    args:
      - 'check'
      - '--manifest-path'
      - '$projectRoot/Cargo.toml'
      - '--all-targets'
      - '--all-features'
      - '--locked'
    inputs:
      - '@globs(sources)'
      - '/Cargo.toml'
      - '/Cargo.lock'

  fmt:
    command: 'cargo'
    args:
      - 'fmt'
      - '--manifest-path'
      - '$projectRoot/Cargo.toml'
      - '--check'
    inputs:
      - '@globs(sources)'
      - '/rustfmt.toml'

  clippy:
    command: 'cargo'
    args:
      - 'clippy'
      - '--manifest-path'
      - '$projectRoot/Cargo.toml'
      - '--all-targets'
      - '--all-features'
      - '--locked'
      - '--'
      - '-D'
      - 'warnings'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '/Cargo.lock'

  test:
    command: 'cargo'
    args:
      - 'test'
      - '--manifest-path'
      - '$projectRoot/Cargo.toml'
      - '--all-targets'
      - '--all-features'
      - '--locked'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '/Cargo.lock'
